import type { OpenNextConfig } from "@opennextjs/cloudflare";

const config: OpenNextConfig = {
    default: {
        override: {
            wrapper: "cloudflare-node",
            converter: "edge",
            proxyExternalRequest: "fetch",
            incrementalCache: "dummy",
            tagCache: "dummy",
            queue: "dummy",
        },
    },
    edgeExternals: [
        "node:async_hooks",
        "node:fs",
        "node:path",
        "node:url",
        "node:vm",
        "node:buffer",
        "node:crypto",
        "node:stream",
        "node:util",
        "node:http",
        "node:https",
        "node:events",
        "node:os",
        "node:tty",
        "node:zlib",
        "node:net",
        "node:dns",
        "async_hooks",
        "fs",
        "path",
        "url",
        "vm",
        "buffer",
        "crypto",
        "stream",
        "util",
        "http",
        "https",
        "events",
        "os",
        "tty",
        "zlib",
        "net",
        "dns",
    ],
    middleware: {
        external: true,
        override: {
            wrapper: "cloudflare-edge",
            converter: "edge",
            proxyExternalRequest: "fetch",
            incrementalCache: "dummy",
            tagCache: "dummy",
            queue: "dummy",
        },
    },
};

export default config;
