import {
  Activity,
  AppWindow,
  Box,
  Calendar,
  Cloud,
  CloudLightning,
  CloudSun,
  Cpu,
  Database,
  Disc,
  FileCode,
  Folder,
  GitBranch,
  GraduationCap,
  Hammer,
  HardDrive,
  Hexagon,
  CircuitBoard,
  Monitor,
  ArrowLeftRight,
  Container,
  GitPullRequest,
  RefreshCw,
  Bot,
  Home,
  Info,
  Infinity as InfinityIcon,
  Kanban,
  Key,
  Landmark,
  Briefcase,
  Layers,
  Link,
  ListOrdered,
  Lock,
  Network,
  PenTool,
  Rocket,
  Save,
  Server,
  Shield,
  Signal,
  LayoutGrid,
  Terminal,
  Zap,
  LayoutTemplate,
  Library,
  MessageSquare,
  Settings,
  Users
} from 'lucide-react';
import type { ReactNode } from 'react';

export const iconMap: Record<string, ReactNode> = {
  Activity: <Activity />,
  AppWindow: <AppWindow />,
  Box: <Box />,
  Calendar: <Calendar />,
  Cloud: <Cloud />,
  CloudLightning: <CloudLightning />, // AWS
  CloudSun: <CloudSun />, // Alibaba
  Signal: <Signal />, // CTyun
  LayoutGrid: <LayoutGrid />, // GCP
  Cpu: <Cpu />,
  Database: <Database />,
  Disc: <Disc />,
  FileCode: <FileCode />,
  Folder: <Folder />,
  GitBranch: <GitBranch />,
  GraduationCap: <GraduationCap />,
  Hammer: <Hammer />,
  HardDrive: <HardDrive />,
  Hexagon: <Hexagon />,
  CircuitBoard: <CircuitBoard />,
  Monitor: <Monitor />,
  ArrowLeftRight: <ArrowLeftRight />, // CI/CD
  Container: <Container />, // Docker
  GitPullRequest: <GitPullRequest />, // Gitlab
  RefreshCw: <RefreshCw />, // CI/CD alternate
  Bot: <Bot />, // Jenkins
  Home: <Home />,
  Info: <Info />,
  Infinity: <InfinityIcon />,
  Kanban: <Kanban />,
  Key: <Key />,
  Landmark: <Landmark />,
  Briefcase: <Briefcase />,
  Layers: <Layers />,
  Link: <Link />,
  ListOrdered: <ListOrdered />,
  Lock: <Lock />,
  Network: <Network />,
  PenTool: <PenTool />,
  Rocket: <Rocket />,
  Save: <Save />,
  Server: <Server />,
  Shield: <Shield />,
  Terminal: <Terminal />,
  Zap: <Zap />,
  // Fallbacks or extras
  LayoutTemplate: <LayoutTemplate />,
  Library: <Library />,
  MessageSquare: <MessageSquare />,
  Settings: <Settings />,
  Users: <Users />
};
